# secret
# users
---
- name: htpasswd情報のSecretを取得
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ secret }}"
    namespace: openshift-config
  register: _secret_info

- name: Secret情報を保存する変数を定義
  set_fact:
    _pre_htpasswd_data: ""

- name: "'{{ secret }}'が存在する場合はその情報をデコード"
  when: _secret_info.resources | length != 0
  set_fact:
    _pre_htpasswd_data: "{{ _secret_info.resources[0].data.htpasswd | b64decode }}"

- name: Secret情報を元にhtpasswdファイルをローカルに作成
  copy:
    content: "{{ _pre_htpasswd_data }}"
    dest: "./htpasswd"

- name: ローカルのhtpasswdファイルにユーザー追加
  htpasswd:
    path: "./htpasswd"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "present"
  loop: "{{ users }}"

- name: ローカルのhtpasswdのデータをエンコードする
  slurp:
    path: "./htpasswd"
  register: _post_htpasswd_data

- name: htpasswdのSecretを編集
  k8s:
    state: present
    namespace: openshift-config
    name: "{{ secret }}"
    definition:
      apiVersion: v1
      kind: Secret
      data:
        htpasswd: "{{ _post_htpasswd_data.content }}"
      type: Opaque
