# htpasswd_secret
# users
---
- name: htpasswd情報のSecretを取得
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ htpasswd_secret }}"
    namespace: openshift-config
  register: _secret_info

- name: "Secret({{ htpasswd_secret }})が存在する場合は以下の処理を実行"
  when: _secret_info.resources | length != 0
  block:
  - name: "'{{ htpasswd_secret }}'が存在する場合はその情報をデコード"
    set_fact:
      _pre_htpasswd_data: "{{ _secret_info.resources[0].data.htpasswd | b64decode }}"

  - name: Secret情報を元にhtpasswdファイルをローカルに作成
    copy:
      content: "{{ _pre_htpasswd_data }}"
      dest: "./htpasswd"

  - name: ローカルのhtpasswdファイルからユーザー削除
    htpasswd:
      path: "./htpasswd"
      name: "{{ item.name }}"
      state: "absent"
    loop: "{{ users }}"

  - name: ローカルのhtpasswdのデータをエンコードする
    slurp:
      path: "./htpasswd"
    register: _post_htpasswd_data

  - name: htpasswdのSecretを編集
    k8s:
      state: present
      namespace: openshift-config
      name: "{{ htpasswd_secret }}"
      definition:
        apiVersion: v1
        kind: Secret
        data:
          htpasswd: "{{ _post_htpasswd_data.content }}"
        type: Opaque
