---
- name: "ClusterRoleBindingを作成"
  k8s:
    state: present
    namespace: openshift-config
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ crb.name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: "{{ crb.clusterrole }}"
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: "{{ user.name }}"
  when: crb.name is defined and crb.clusterrole is defined
  loop: "{{ user.crbs }}"
  loop_control:
    loop_var: "crb"
